language: python
python:
  - "3.6"
# command to install dependencies
install:
  - pip install -r requirements.txt
 # - pip install coveralls
 # - pip install codecov

# command to run tests
script: 
  - pytest
#  - py.test --cov=Thebucketlist-reboot tests/
#  - py.test tests/ --doctest-modules --pep8 app -v --cov app --cov-report term-missing
#  - coverage run tests/
after_success:
  - coveralls
  - codecov