language: python
python:
  - "3.6"
# command to install dependencies
install:
  - pip install -r requirements.txt
  - pip install coveralls
  - pip install codecov

# command to run tests
script: 
  - py.test --cov=./
after_success:
  - coveralls
  - codecov